"""add_user_residual_tables

Revision ID: 068541073a8b
Revises: 12c86426176b
Create Date: 2025-12-26 18:24:54.577085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068541073a8b'
down_revision = '12c86426176b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity_residuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=50), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('total_elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('physics_model_version', sa.String(length=20), nullable=False),
    sa.Column('recency_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activity_residuals', schema=None) as batch_op:
        batch_op.create_index('idx_user_date', ['user_id', 'activity_date'], unique=False)
        batch_op.create_index('idx_user_version', ['user_id', 'physics_model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_residuals_activity_date'), ['activity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_residuals_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_residuals_user_id'), ['user_id'], unique=False)

    op.create_table('user_learned_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('v_flat', sa.Float(), nullable=False),
    sa.Column('k_up', sa.Float(), nullable=True),
    sa.Column('k_tech', sa.Float(), nullable=True),
    sa.Column('a_param', sa.Float(), nullable=True),
    sa.Column('k_terrain_up', sa.Float(), nullable=True),
    sa.Column('k_terrain_down', sa.Float(), nullable=True),
    sa.Column('k_terrain_flat', sa.Float(), nullable=True),
    sa.Column('fatigue_alpha', sa.Float(), nullable=True),
    sa.Column('n_activities_used', sa.Integer(), nullable=False),
    sa.Column('optimization_score', sa.Float(), nullable=True),
    sa.Column('param_uncertainties', sa.JSON(), nullable=True),
    sa.Column('last_trained', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_residual_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_blob', sa.LargeBinary(), nullable=False),
    sa.Column('n_activities_used', sa.Integer(), nullable=False),
    sa.Column('n_segments_trained', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('model_config', sa.JSON(), nullable=True),
    sa.Column('last_trained', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_residual_models')
    op.drop_table('user_learned_params')
    with op.batch_alter_table('user_activity_residuals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activity_residuals_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_residuals_activity_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_residuals_activity_date'))
        batch_op.drop_index('idx_user_version')
        batch_op.drop_index('idx_user_date')

    op.drop_table('user_activity_residuals')
    # ### end Alembic commands ###
