"""add residual_variance to user_residual_model

Revision ID: 3966644a58f3
Revises: 3d80f6721f07
Create Date: 2026-01-01 12:53:31.733373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3966644a58f3'
down_revision = '3d80f6721f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_residual_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residual_variance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_residual_models', schema=None) as batch_op:
        batch_op.drop_column('residual_variance')

    # ### end Alembic commands ###
