"""add excluded_from_training to user_activity_residual

Revision ID: 3d80f6721f07
Revises: 068541073a8b
Create Date: 2026-01-01 12:30:07.292371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d80f6721f07'
down_revision = '068541073a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_residuals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excluded_from_training', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_residuals', schema=None) as batch_op:
        batch_op.drop_column('excluded_from_training')

    # ### end Alembic commands ###
