"""Add fatigue_curve to performance_snapshots

Revision ID: 5c67ce523425
Revises: 
Create Date: 2025-12-24 10:15:24.042763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c67ce523425'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fatigue_curve', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_snapshots', schema=None) as batch_op:
        batch_op.drop_column('fatigue_curve')

    # ### end Alembic commands ###
