"""sync models with removed columns

Revision ID: ce6c2880e7ca
Revises: a1b2c3d4e5f6
Create Date: 2026-01-18 09:20:48.627678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ce6c2880e7ca'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Delete incomplete predictions before adding NOT NULL constraints
    op.execute("DELETE FROM predictions WHERE flat_pace IS NULL OR total_time_seconds IS NULL OR predicted_segments IS NULL")

    with op.batch_alter_table('gpx_files', schema=None) as batch_op:
        batch_op.drop_column('prediction_id')
        batch_op.drop_column('error_message')
        batch_op.drop_column('processing_status')

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.alter_column('flat_pace',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('total_time_seconds',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('predicted_segments',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.drop_column('tier')
        batch_op.drop_column('prediction_data')
        batch_op.drop_column('effort_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effort_level', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('prediction_data', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tier', sa.INTEGER(), nullable=True))
        batch_op.alter_column('predicted_segments',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('total_time_seconds',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('flat_pace',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('gpx_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'"), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('prediction_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
